v1 = input('Digite qualquer coisa! ')
print('O tipo primitivo desse valor é ',type(v1))
print('Só tem espaço? ', v1.isspace())
print('É um número?', v1.isnumeric())
print('É alfabético?', v1.isalpha())
print('É alfanumerico?', v1.isalnum())
print('É maiúsculas?', v1.isupper())
print('É minúsculas?', v1.islower())
print('É capitalizada?', v1.istitle())
